"""
Pydantic models for request and response validation.
"""

from typing import List, Optional

from pydantic import BaseModel, Field


class QuestionRequest(BaseModel):
    """Incoming question payload for /ask and /ask/stream.

    Length/empty validation is handled in the service layer so we can return
    the assignment's specific 400 error messages instead of a generic 422.
    """

    question: str = Field(
        ...,
        description="Student question",
    )
    session_id: Optional[str] = Field(
        default=None,
        description="Session id; generated by the server when omitted.",
    )
    file_content: Optional[str] = Field(
        default=None,
        description="Optional inline document text to use as temporary context.",
    )


class AnswerResponse(BaseModel):
    """Response returned by /ask."""

    question: str
    answer: str
    source: str = Field(description="Where the answer came from: FAQ or LLM.")
    session_id: str
    timestamp: str
    response_time: float
    retrieved_context: Optional[List[str]] = None


class HealthResponse(BaseModel):
    """Response returned by /health."""

    status: str
    backend: str
    ollama: str
    model: str
    rag_ready: bool
    timestamp: str
    response_time: float


class FeedbackRequest(BaseModel):
    """User feedback rating payload for /feedback."""

    session_id: str = Field(..., min_length=1)
    rating: str = Field(
        ...,
        description="One of: good, average, poor.",
    )
    comment: Optional[str] = Field(default=None, max_length=2000)


class ModelSelectRequest(BaseModel):
    """Payload for selecting or pulling a model."""

    model: str = Field(..., min_length=1, max_length=120)


class UploadResponse(BaseModel):
    """Response returned by /upload."""

    session_id: str
    filename: str
    chunks_indexed: int
    message: str


class ChatHistory(BaseModel):
    question: str
    answer: str
    source: str
    response_time: float
    timestamp: str


class HistoryResponse(BaseModel):
    session_id: Optional[str] = None
    history: List[ChatHistory]


class ErrorResponse(BaseModel):
    """Standard error envelope used by exception handlers."""

    error: str
    detail: Optional[str] = None


# ==========================
# Authentication
# ==========================

class RegisterRequest(BaseModel):
    """Account registration payload for /auth/register."""

    username: str = Field(..., min_length=3, max_length=64)
    password: str = Field(..., min_length=6, max_length=128)
    display_name: Optional[str] = Field(default="", max_length=80)
    email: Optional[str] = Field(default="", max_length=120)


class LoginRequest(BaseModel):
    """Login payload for /auth/login."""

    username: str = Field(..., min_length=1)
    password: str = Field(..., min_length=1)


class UserPublic(BaseModel):
    """Public, safe-to-expose user fields (never includes the password hash)."""

    username: str
    display_name: str
    email: str = ""
    role: str = "student"
    created_at: str = ""


class AuthResponse(BaseModel):
    """Returned by /auth/register and /auth/login."""

    token: str
    token_type: str = "bearer"
    expires_in: int
    user: UserPublic


# ==========================
# Chat history / sessions
# ==========================

class SessionSummary(BaseModel):
    """A chat session as shown in the history sidebar."""

    session_id: str
    title: str
    created_at: str
    updated_at: str
    message_count: int = 0


class SessionListResponse(BaseModel):
    sessions: List["SessionSummary"]


class SessionMessage(BaseModel):
    """A single stored message when reloading a conversation."""

    role: str
    content: str
    source: Optional[str] = None
    response_time: Optional[float] = None
    tokens_per_second: Optional[float] = None
    model: Optional[str] = None
    contexts: Optional[List[dict]] = None
    created_at: str


class SessionDetailResponse(BaseModel):
    session_id: str
    title: str
    messages: List["SessionMessage"]


# ==========================
# RAG document management (admin)
# ==========================

class RagDocument(BaseModel):
    """Metadata for a document indexed in the knowledge base."""

    doc_id: str
    filename: str
    size: int
    chunks: int
    uploaded_by: str = ""
    uploaded_at: str = ""


class RagDocumentList(BaseModel):
    documents: List["RagDocument"]
    rag_ready: bool


class DocumentContentResponse(BaseModel):
    """Full document text for the source-reference viewer."""

    doc_id: str
    filename: str
    text: str


# ==========================
# Suggestions
# ==========================

class SuggestionsResponse(BaseModel):
    suggestions: List[str]
